#pragma once

#define VLC_VERSION_MAJOR 2
#define VLC_VERSION_MINOR 1
#define VLC_VERSION_PATCH 1
#define VLC_COMMIT_HASH "unknown"

#define VLC_VERSION (VLC_VERSION_MAJOR * 1000 + VLC_VERSION_MINOR * 100 + VLC_VERSION_PATCH)
#define VLC_VERSION_STRING "v2.1.1"
